name: ğŸš€ Deploy ke Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ” Checkout kode (non-shallow)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ambil seluruh history, penting!

      - name: ğŸ” Push ke Hugging Face
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          git remote add hf https://LuckySepthiano:${{ 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 }}@huggingface.co/spaces/Thians/111
          git push -f hf main



Ganti `your-username/php-website-anda` dengan format: `LuckySepthiano/111'

Contoh: `budi/php-praktik-1`
